# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 18:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lectura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tems', models.DateTimeField(default=datetime.datetime(2018, 9, 6, 18, 15, 27, 333286))),
                ('RPM', models.IntegerField(max_length=40000)),
                ('SOC', models.IntegerField(max_length=500)),
                ('Tbat', models.IntegerField(max_length=500)),
                ('Tdriver', models.IntegerField(max_length=500)),
                ('Tengine', models.IntegerField(max_length=500)),
                ('Vbat', models.IntegerField(max_length=1000)),
                ('Imax', models.IntegerField(max_length=5000)),
                ('Vmincell', models.IntegerField(max_length=10000)),
                ('Vmaxcell', models.IntegerField(max_length=10000)),
                ('Tmincell', models.IntegerField(max_length=10000)),
                ('Tmaxcell', models.IntegerField(max_length=10000)),
            ],
        ),
    ]
